//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrder
    {
        public int OrderID { get; set; }
        public System.DateTime DateAndTimeOfOrder { get; set; }
        public int TotalPrice { get; set; }
        public string CustomerJMBG { get; set; }
        public string OrderStatus { get; set; }
    }
}
